[environments.test]
url = "jdbc:postgresql://localhost:54320/testing"
user = "testing"
password = "password"

[environments.dev]
url = "jdbc:postgresql://localhost:5432/dev"
user = "dev"
password = "password"

[flyway]
environment = "dev"
locations = ["filesystem:./sql/default"]
cleanDisabled = false